### ISSUE TITLE
Add Serialization to other models 

### ISSUE THREAD

**Issue by philschmid** [aws-neuron/transformers-neuronx#14]
Hello, is there any easy way to add serialization to models other than GPT2? 
GPT2 has a `_save_compiled_artifacts` method to save compiled artifacts to disk and load. That would be convenient for other models as well since compiling, e.g. GPT-J takes, 5-10 minutes. 

I looked at the code but it seems there was a design change.

**Comment by aws-ennst** [comment]
Thank you for reaching out. We have this in the roadmap and will let you know when it is available.

**Comment by mrnikwaws** [comment]
Latest release includes serialization: https://awsdocs-neuron.readthedocs-hosted.com/en/latest/release-notes/index.html#latest-neuron-release
