### ISSUE TITLE
GPT2: sampling using transformers generate() significantly slower than using model.sample()

### ISSUE THREAD

**Issue by dacorvo** [aws-neuron/transformers-neuronx#15]
Following the example of `HuggingFaceGenerationModelAdapter`, I have created a `NeuronModelForCausalLM` adapter class for HuggingFace optimum-neuron (see https://github.com/huggingface/optimum-neuron/pull/117).

I compared the inference times of calling the `GPT2ForSampling.sample()` method directly and using the `generate()` method.

| @inf2.8xlarge| sample | generate |
|-------------|--------|----------|
| 128 tokens  | 0.5 s  | 0.9 s    |
| 1000 tokens | 4.5 s  | 7.4 s    |

Calling `generate()` through the wrapper is significantly slower: is this expected ? Did I miss something ?

**Comment by mrnikwaws** [comment]
Hi @dacorvo,

Could you also share the parameters you call the GPT2ForSampling.sample() and generate()?

The default behavior of sample and generate is significantly different:
 *.sample() uses topk (k=50)
* to use same topk in generate, it would expect generate(topk=50)

It would be really helpful if you could share the minimum script including these commands, and the instance type you used to reproduce your profiling results.

**Comment by dacorvo** [comment]
Hi @mrnikwaws, thank you for your answer.

I think `top_k` is by default set to 50 in transformers. I set it explicitly anyway, but I got the same results.

Here is the link to my script: https://github.com/dacorvo/transformers-neuronx/blob/inference_tests/test_gpt2.py

**Comment by dacorvo** [comment]
I did a few more tests on an **24xlarge** instance, which has 6 devices / 12 cores.

Using a batch size of 16 and generating 1000 tokens, the test lasts long enough so that I can get meaningful numbers using neuron_top in paralell.

What I see is that when using the `GPT2ForSampling.sample()` method directly, the 12 cores are used up to **60 %**, while when using the wrapper `generate()` method, they are only used up to **20 %** (virtual CPU usage looks equivalent).

This is purely speculative, because I have no idea of what actually happens behind the scene, but in a previous life developing software for accelerators, this was often the sign of too much latency in the host process feeding the hardware.

**Comment by dacorvo** [comment]
I investigated a bit further and the top-k sampling code is indeed much slower in transformers, which creates latency between the hardware invocations. I think I might have identified why the `sample_loop()` is faster and I will see if I can align the transformers top-k implementation, and confirm this solves this issue.

**Comment by mrnikwaws** [comment]
Thanks @dacorvo we'll keep the ticket open in the interim, but will assume you have the next step

**Comment by dacorvo** [comment]
I have modified the transformers sampling loop in `optimum-neuron`:
https://github.com/huggingface/optimum-neuron/pull/130
The performances of the generation through `transformers` `generate()` are now equivalent to those using the `transformers-neuronx` custom sampling loop.
FYI, I submitted the issue to the `transformers` team but at this stage it is not going to be integrated in the core library.

**Comment by mrnikwaws** [comment]
Thanks @dacorvo we're taking a look at what we can do to alert customers on this issue in our docs / through warning messages.
