### ISSUE TITLE
Support for MPT models

### ISSUE THREAD

**Issue by averypelle** [aws-neuron/transformers-neuronx#25]
Hi AWS Team,

Very cool project and I am looking forward to using it! Are you planning to add support for MPT-based models?

Thanks!

**Comment by aws-maens** [comment]
MPT is a decoder model , for training please use the Neuron Distributed library ( https://awsdocs-neuron.readthedocs-hosted.com/en/latest/libraries/neuronx-distributed/index.html). Please open an issue if you face an issue.
Inference  should be supported in the next releases as part of the Transformers Neuron and the Neuron Distributed libraries.
