### ISSUE TITLE
Corrupted output with llama prototype model

### ISSUE THREAD

**Issue by dacorvo** [aws-neuron/transformers-neuronx#30]
I understand the llama model is still a 'prototype', so it is expected to have some issues when running it.

I am nevertheless creating this issue hoping that my tests will help fixing them.

I am using [openlm-research/open_llama_3b](https://huggingface.co/openlm-research/open_llama_3b) for a simple text-generation.

I am using the `transformers-neuronx` [main branch](https://github.com/aws-neuron/transformers-neuronx/commit/d3f6e49586e717b211a4df6c8c9230a232507825).
`The neuronx-cc` compiler version is `2.8.0.25+a3ad0f342`.

The model is compiled with `batch_size = 1`, `amp = 'f16'`, `tp_degree = 2`.

I use `transformers.set_seed(42)` to get reproducible results, using the same `"One of my fondest memory is"` prompt.

If I generate only 128 tokens, I get something that looks ok:

```
'<s> One of my fondest memory is my school time. Before I went to college, I was studying at Kofu Municipal Technical
 School in the north part of Yamanashi. It was a small school (about 300 students) but it was very cozy. Not just the school
 building, but the area where the school was situated was very calm and I was very happy living in that area.\nMy father
 was the principal of the school. I was a senior high school student and I got married when I was 19 years old. My father
 died when I was 35 years old. I stayed in'
```

But if I increase the number of generated tokens, the output tokens are duplicated or corrupted (here starting from token `133`):

```
'<s> One of my fondest memory is my school time. Before I went to college, I was studying at Kofu Municipal Technical
 School in the north part of Yamanashi. It was a small school (about 300 students) but it was very cozy. Not just the school
 building, but the area where the school was situated was very calm and I was very happy living in that area.\nMy father
 was the principal of the school. I was a senior high school student and I got married when I was 19 years old. My father
 died when I was 35 years old. I stayed in that area until Iw at his office from 39 at least 568833 years later on this blog,
 I I’ The school'
```
The more tokens I generate, the worse it gets.

**Comment by hannanjgaws** [comment]
Hi @dacorvo:

Thank you for reporting this issue. We are looking into this, and we expect to have a fix in an upcoming release. We will update this ticket when this issue has been resolved.

**Comment by jeffhataws** [comment]
Thanks @dacorvo . Looks like you are able to get batch 1 and 2 working with latest release 2.13 version of transformers-neuronx. We will track the batch size > 2 issue with https://github.com/aws-neuron/transformers-neuronx/issues/34 . In the meantime, I will close this ticket.
