### ISSUE TITLE
How to set: FI_EFA_FORK_SAFE=1 ?

### ISSUE THREAD

**Issue by yogendra-yatnalkar** [aws-neuron/transformers-neuronx#37]
Hi team, I was recently playing with Llama 2 on **inf2.24xlarge** instance. The AMI I am currently using is: [AWS Deep Learning AMI Neuron PyTorch 1.13 (Amazon Linux 2)](https://aws.amazon.com/releasenotes/aws-deep-learning-ami-neuron-pytorch-1-13-amazon-linux-2/).

The Llama2 model is getting compiled and running successfully. While running the model, I also observed the instance performance using **neuron-top**, and the model seems to be utilizing all the neuron-cores from all neuron-core-devices. 

But, while compiling the model, I get the following message: 

```
2023-Sep-05 13:08:49.0371 20080:29631 [0] init.cc:97 CCOM WARN Linux kernel 5.10 requires setting FI_EFA_FORK_SAFE=1 environment variable.  Multi-node support will be disabled.
Please restart with FI_EFA_FORK_SAFE=1 set.
```

Can someone please guide me in understanding if this is something of concern and if yes how to resolve this ?

**Comment by jeffhataws** [comment]
Hi @yogendra-yatnalkar, you can set FI_EFA_FORK_SAFE the same way you are setting other environment variables that control the compilation and execution.  However, the setting is only applicable to EFA and has no effect if your model runs on a single instance, in which case your can ignore the warning.

**Comment by yogendra-yatnalkar** [comment]
Hi @jeffhataws, understood the point, thankyou.
