### ISSUE TITLE
Support for Mistral-7B model

### ISSUE THREAD

**Issue by henghui-zhu-amazon** [aws-neuron/transformers-neuronx#50]
Hi AWS Neuron team,

It would be great to have Mistral-7B model support since its performance is better than LLAMA2 and it is with a better license. Will this model be on the roadmap?

Best,
Henry

**Comment by aws-taylor** [comment]
Hello @henghui-zhu-amazon,

 Mistral is on our internal roadmap - we'll be adding a roadmap item to Github soon and will update this issue with a reference.
 
 -Taylor

**Comment by gsnaws** [comment]
Beta support added in 2.16 release - https://awsdocs-neuron.readthedocs-hosted.com/en/latest/release-notes/index.html#latest-neuron-release

**Comment by aws-rhsoln** [comment]
Please check the support added in 2.16 release. Closing the ticket. PLease reopen if you still see the issue.
