### ISSUE TITLE
Support for encoder-decoder models

### ISSUE THREAD

**Issue by kwontaek-amazon** [aws-neuron/transformers-neuronx#51]
Hi team,

I wondered if the tool has support for any encoder-decoder models too (like FLAN-T5 or FLAN-UL2)?
If not at the moment, do you have a plan for it?

Thanks!

**Comment by aws-donkrets** [comment]
Hi [kwontaek-amazon](https://github.com/kwontaek-amazon) - We support T5 models and you can find a tutorial on it [here](https://awsdocs-neuron.readthedocs-hosted.com/en/latest/src/examples/pytorch/torch-neuronx/t5-inference-tutorial.html?highlight=FLAN). However we are working on updating this tutorial to support the flan-t5 models. Expect that to be completed in a future release.

**Comment by aws-maens** [comment]
Hi @kwontaek-amazon , encoder-decoder models inference like T5 are supported using NeuronX Distributed library, please see [T5 Tutorial](https://awsdocs-neuron.readthedocs-hosted.com/en/latest/src/examples/pytorch/torch-neuronx/t5-inference-tutorial.html?highlight=FLAN) in the Neuron documentation. Encoder-decoder models are not part of Transformers NeuronX current roadmap.
