### ISSUE TITLE
Serving Throughput Optimizations (e.g. PagedAttention)

### ISSUE THREAD

**Issue by vigneshv59** [aws-neuron/transformers-neuronx#52]
Projects like vLLM help optimize model serving throughput, I was wondering if implementing PagedAttention or integrating with vLLM was something that was on your roadmap to improve using the Inf2 processors in production?

**Comment by jyang-aws** [comment]
@vigneshv59 
sorry for the late reply. we're actively working on it and we have plans for supporting this in a future release.
Will keep you posted once it's ready.

**Comment by aws-maens** [comment]
@vigneshv59 - To clarify the answer above, we are actively working on Continues Batching, PagedAttention is a backlog item for now.

**Comment by aws-rhsoln** [comment]
We have added an example of continuous batching using VLLM here: https://awsdocs-neuron.readthedocs-hosted.com/en/latest/libraries/transformers-neuronx/transformers-neuronx-developer-guide-for-continuous-batching.html 
Closing this ticket. Please re-open if there are any further issues.
