### ISSUE TITLE
Mixtral config issue -- not handling null well

### ISSUE THREAD

**Issue by jimburtoft** [aws-neuron/transformers-neuronx#71]
The default config for https://huggingface.co/mistralai/Mixtral-8x7B-v0.1/config.json has 
`"sliding_window": null, `

(this is defined at 4096 in Mistral)

This causes a syntax error because hlo.py checks it against something (window_size is set to config.sliding_window_size somewhere else) (see below).  There also seems to be some code elsewhere to set a default, but maybe it doesn't work because the value was already assigned as null?  

I can't override it by passing it in.  I had to edit the local config.json to set it to 4096 to get past the syntax error (I got a compilation error later on, but that is a different issue)

I don't know why the model config on Hugging Face includes it, but has it set to null. 

I think if the code needs to do that check, it should verify the value in config to at least make sure it exists, or generate a better error.

Using 
transformers                  4.37.0.dev0
transformers-neuronx          0.9.20240104
on the Hugging Face DLAMI image.

Code to replicate:
```
import torch
from transformers_neuronx import constants
from transformers_neuronx.mixtral.model import MixtralForSampling
from transformers_neuronx.module import save_pretrained_split
from transformers_neuronx.config import NeuronConfig
from transformers_neuronx.mixtral.config import MixtralConfig
from transformers import AutoModelForCausalLM, AutoTokenizer

neuron_config = NeuronConfig(
    grouped_query_attention=constants.GQA.SHARD_OVER_HEADS
)

model_cpu = AutoModelForCausalLM.from_pretrained('Mixtral-8x7B-v0.1')
save_pretrained_split(model_cpu, 'Mixtral-8x7B-v0.1-split')

model_neuron = MixtralForSampling.from_pretrained('Mixtral-8x7B-v0.1-split', batch_size=1, \
     tp_degree=8, n_positions=256, amp='bf16', sliding_window = 4096, neuron_config=neuron_config)


model_neuron.to_neuron()

```
Error:
```>>> model_neuron.to_neuron()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ubuntu/.local/lib/python3.8/site-packages/transformers_neuronx/base.py", line 67, in to_neuron
    self.load_weights()
  File "/home/ubuntu/.local/lib/python3.8/site-packages/transformers_neuronx/mixtral/model.py", line 135, in load_weights
    self.decoder_lm_head.to_neuron()
  File "/home/ubuntu/.local/lib/python3.8/site-packages/transformers_neuronx/decoder.py", line 290, in to_neuron
    self.program = self._build_program()
  File "/home/ubuntu/.local/lib/python3.8/site-packages/transformers_neuronx/decoder.py", line 423, in _build_program
    hlo_modules[npos,batch_size] = self._hlo_fully_unrolled(npos, batch_size)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/transformers_neuronx/decoder.py", line 473, in _hlo_fully_unrolled
    return compiler.compile_py_func(fully_unrolled)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/transformers_neuronx/compiler.py", line 48, in compile_py_func
    return HloScribe(serialize_torch)(py_func).module_proto
  File "/usr/local/lib/python3.8/dist-packages/torch_neuronx/pyhlo/scribe.py", line 265, in __call__
    scribe.scribe(func)
  File "/usr/local/lib/python3.8/dist-packages/torch_neuronx/pyhlo/scribe.py", line 277, in scribe
    root_shape = compute_def(self)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/transformers_neuronx/decoder.py", line 463, in fully_unrolled
    hidden, out_caches = self._hlo_layers(hidden, tensors, self.layers, layers_caches, layers_weights)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/transformers_neuronx/decoder.py", line 526, in _hlo_layers
    hidden, *out_caches = self.layer_builder(hidden, *tensors, *in_caches, *weights)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/transformers_neuronx/mixtral/hlo.py", line 85, in layer
    attn_output, out_attn_k_cache, out_attn_v_cache = self.attention(
  File "/home/ubuntu/.local/lib/python3.8/site-packages/transformers_neuronx/mistral/hlo.py", line 178, in attention
    if list(cached_keys.sizes)[0] > self.config.window_size and list(cached_values.sizes)[0] > self.config.window_size and list(mask.sizes)[2] >self.config.window_size:
TypeError: '>' not supported between instances of 'int' and 'NoneType'
```

**Comment by mike-zhang-aws** [comment]
We have identified a fix which will be available in an upcoming release. Thanks.

**Comment by hjoneal** [comment]
Hi Mike, I'm having the exact same issue as Jim with Mixtral --> Neuronx.  Do you have any information on when a fix might be issued?  Or any workaround?  Thanks

**Comment by mike-zhang-aws** [comment]
Hi @hjoneal, the fix will be available in the upcoming release.

**Comment by mgomes** [comment]
@mike-zhang-aws how often do you all cut releases? I see a minor bump from Jul 2023. Is there a beta channel?

**Comment by aws-donkrets** [comment]
Hi [mgomes](https://github.com/mgomes)  You can find more info about the transformers-neuronx releases here - https://awsdocs-neuron.readthedocs-hosted.com/en/latest/release-notes/torch/transformers-neuronx/index.html?highlight=transformers-neuronx

Also, we cut new Neuron SDK releases on an approximately monthly basis. You can see the previous SDK releases and their contents at https://awsdocs-neuron.readthedocs-hosted.com/en/latest/release-notes/prev/rn.html#prev-rn

**Comment by jimburtoft** [comment]
This issue was fixed in the latest version of transformers.  To fix I ran:
`pip install -U transformers-neuronx --extra-index-url=https://pip.repos.neuron.amazonaws.com`

I saw:
```
Successfully uninstalled transformers-neuronx-0.9.474
Successfully installed transformers-neuronx-0.10.0.21
```

**Comment by jluntamazon** [comment]
Thanks for validating the fix @jimburtoft!

Closing this issue since it appears to be resolved.
