### ISSUE TITLE
`stopping_criteria_list(input_ids, probs)` does not check for the correct sequence.

### ISSUE THREAD

**Issue by michaelfeil** [aws-neuron/transformers-neuronx#75]
https://github.com/aws-neuron/transformers-neuronx/blob/8b01968f57ba29b8e3365e5a1424b74382ae8902/src/transformers_neuronx/sampling.py#L335

Huggingface transformers gives the option to stop a sequence based on the generated tokens. 
`stopping_criteria_list(input_ids, probs)`
In this case, we do not grow the `input_ids`, the callback is executed also on the `input_ids`. 

Why not make the callback on 

```python
if stopping_criteria_list(torch.cat(tokens, dim=-1), probs):
            break
```

**Comment by jluntamazon** [comment]
Hi @michaelfeil,

We can look into supporting this. One alternative option we provide is the ability to use the huggingface generation loop directly. This allows you to use any functionality that is supported by the traditional [GenerationMixin.generate()](https://huggingface.co/docs/transformers/v4.37.1/en/main_classes/text_generation#transformers.GenerationMixin.generate) method as-is.

An example of how this is used can be found here:
[https://awsdocs-neuron.readthedocs-hosted.com/en/latest/libraries/transformers-neuronx/transformers-neuronx-developer-guide.html#hugging-[…]-support](https://awsdocs-neuron.readthedocs-hosted.com/en/latest/libraries/transformers-neuronx/transformers-neuronx-developer-guide.html#hugging-face-generate-api-support)

**Comment by michaelfeil** [comment]
Thanks @jluntamazon - the pointer to the mixin is good. Now that `optimum[neuronx]` is released, we might roll with that one.

**Comment by jyang-aws** [comment]
Closing the issue for now, please re-open if you see further issues.

**Comment by michaelfeil** [comment]
@jyang-aws Well the implementation of `stopping_criteria_list(input_ids, probs)` is actually incorrect / doing something unexected vs transformers library.
